### ISSUE TITLE
video.py & wideo.py

### ISSUE THREAD

**Issue by XUPEIZIYAN** [Szymon-Groch/RoadSign_detector#1]
in main.py there is python_files = {
    1: "camera.py",
    2: "video.py",
}
but their is no such file , the name is wideo.py

**Comment by Szymon-Groch** [comment]
I meant wideo.py naturally. During writing my engineering thesis I changed "video.py" file into "wideo.py". Most likely I fixed this issue during testing on other PC with linux a while back but it remained on my pc which I uploaded on git.


Fixed it ^^
and thx for pointing this out
